apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-micro
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: spring-micro
    spec:
      containers:
      - name: simple-pod
        image: genedocker/simple-service:v4
        ports:
        - containerPort: 8080
